options:
  default_pose: [0.62, 0.005, 1.43, 0.99, 0.05, -0.1, -0.003]
  object_tolerance: 0.1
  references_file: ""
  solver_config_file: ""
  gaussian_policy: true
  debug_prints: false

dynamics:
  # the simulation dt should be a divisor of the controller dt
  dt: 0.0015
  robot_description_raisim: ""
  object_description_raisim: ""
  ignore_panda_self_collision: false
  ignore_object_self_collision: true
  robot_description: ""
  object_description: ""
  raisim_object_res_path: ""
  raisim_robot_res_path: ""
  object_handle_link: handle_link
  object_handle_joint: handle_joint
  articulation_joint: articulation_joint
  initial_state: [ -1.5, 0.0, 0.0, 0.0, -0.52, 0.0, -1.785, 0.0, 1.10, 0.69, 0.04, 0.04,    # robot position
                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,             # robot velocity
                   0.0,                                                                    # object joint position
                   0.0,                                                                    # object joint velocity
                   0,                                                                      # contact flag
                   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]             # external torques

cost:
  regularization: 0.0
  linear_weight: 100.0
  linear_weight_opening: 10.0

  angular_weight: 10.0
  angular_weight_opening: 1.0

  # joint controller cost (mode 3)
  arm_joint_weight: 20
  robot_base_position_weight: 20
  robot_base_orientation_weight: 20

  # reach cost, minimum and maximum reach
  min_dist: 0.4
  max_reach: 1.0
  reach_weight: 100
  reach_weight_slope: 10

  obstacle_weight: 0
  obstacle_weight_slope: 0
  obstacle_radius: 0.8

  contact_weight: 10.0

  object_weight: 1000
  object_tolerance: 0.01

  grasp_translation_offset: [ 0.0, 0.0, 0.0 ] # unused
  grasp_orientation_offset: [ 0, -0.7071068, 0, 0.7071068 ]    # unused

  upper_joint_limits: [ 2.0, 2.0, 6.28, 2.8973, 1.7628, 2.8973, 0.0698, 2.8973, 3.7525, 2.8973 ]
  lower_joint_limits: [ -2.0, -2.0, -6.28, -2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973 ]

  joint_limit_cost: 1000 #1000
  joint_limit_slope: 1000000 #100

  max_power: 0.0
  power_weight: 0.0

  handle_frame: handle_link
  tracked_frame: panda_grasp
  arm_base_frame: panda_link0

  collision_link_0: panda_link1
  collision_link_1: panda_link7
  collision_threshold: 0.35
  collision_weight: 1000

  debug_prints: false
